<?php

namespace Pulli\TimmeSoapClient\Resources;

use Pulli\TimmeSoapClient\Enums\BackupAction;
use Pulli\TimmeSoapClient\Enums\Status;
use Pulli\TimmeSoapClient\Resource;

/**
 * `sites_web_domain_*` — web vhosts. Most fields on the domain record are
 * regenerated by ISPConfig on save; only edit the fields you mean to change.
 */
class Sites extends Resource
{
    /**
     * Fetch a vhost by `domain_id`.
     *
     * @return array<string, mixed>
     */
    public function find(int $domainId): array
    {
        return $this->call('sites_web_domain_get', $domainId);
    }

    /**
     * Look up a vhost by its domain string. Returns null if not found.
     *
     * @return array<string, mixed>|null
     */
    public function findByDomain(string $domain): ?array
    {
        $rows = $this->call('sites_web_domain_get', ['domain' => $domain]);
        if (empty($rows)) {
            return null;
        }

        return is_array($rows[0] ?? null) ? $rows[0] : $rows;
    }

    /**
     * Create a new web vhost. Returns the new `domain_id`.
     *
     * @param  array<string, mixed>  $params
     */
    public function add(int $clientId, array $params, bool $readonly = false): int
    {
        return (int) $this->call('sites_web_domain_add', $clientId, $params, $readonly);
    }

    /**
     * Update arbitrary fields on an existing vhost. ISPConfig regenerates
     * the on-disk vhost + reloads nginx asynchronously after a successful
     * update (~30–60s).
     *
     * @param  array<string, mixed>  $params
     */
    public function update(int $clientId, int $domainId, array $params): bool
    {
        return (bool) $this->call('sites_web_domain_update', $clientId, $domainId, $params);
    }

    public function delete(int $domainId): bool
    {
        return (bool) $this->call('sites_web_domain_delete', $domainId);
    }

    /**
     * Toggle a vhost between Active and Inactive. ISPConfig regenerates the
     * nginx config + reloads asynchronously.
     */
    public function setStatus(int $domainId, Status $status): mixed
    {
        return $this->call('sites_web_domain_set_status', $domainId, $status->value);
    }

    /**
     * Force ISPConfig to regenerate the on-disk vhost from the current
     * record. Useful after templating changes that the panel hasn't
     * detected as needing a regen.
     */
    public function recreateVhost(int $domainId): mixed
    {
        return $this->call('sites_web_domain_recreate_vhost', $domainId);
    }

    // ── Vhost backups (sites_web_domain_backup_*) ─────────────────────

    /** @return array<int, array<string, mixed>> */
    public function backupList(int $domainId): array
    {
        $r = $this->call('sites_web_domain_backup_list', $domainId);

        return is_array($r) ? $r : [];
    }

    /**
     * Trigger a backup action on an existing backup record. Use:
     *   - BackupAction::BackupDownload to materialise the archive on disk
     *   - BackupAction::BackupDownloadLink to get a signed download URL
     *   - BackupAction::BackupRestore to restore the backup over the live site
     */
    public function backup(int $backupId, BackupAction $action): mixed
    {
        return $this->call('sites_web_domain_backup', $backupId, $action->value);
    }

    /** Convenience: download-link shortcut. Returns a signed URL. */
    public function backupDownloadLink(int $backupId): string
    {
        return (string) $this->backup($backupId, BackupAction::BackupDownloadLink);
    }

    /**
     * Toggle the `backup_active` flag for a site (enables/disables future
     * scheduled backups). ISPConfig returns the affected record.
     *
     * @return array<string, mixed>|mixed
     */
    public function backupActive(int $serverId, int $domainId): mixed
    {
        return $this->call('sites_web_domain_backup_active', $serverId, $domainId);
    }

    /**
     * Trigger an immediate backup (outside the schedule). Both website
     * files and the linked database back up by default.
     */
    public function instantBackup(
        int $serverId,
        int $domainId,
        bool $backupWebsite = true,
        bool $backupDatabase = true,
    ): mixed {
        return $this->call(
            'sites_web_domain_instant_backup', $serverId, $domainId, $backupWebsite, $backupDatabase,
        );
    }

    /**
     * Set the vhost's `web_folder` (e.g. "myapp/current/public" to point at
     * a Deployer release symlink). Idempotent — returns false if the value
     * already matches, true if updated.
     */
    public function setWebFolder(int $clientId, int $domainId, string $webFolder): bool
    {
        $site = $this->find($domainId);
        if (($site['web_folder'] ?? null) === $webFolder) {
            return false;
        }
        $site = $this->stripSysFields($site);
        $site['web_folder'] = $webFolder;
        $site['client_group_id'] = $this->client->clients->groupId($clientId);
        $this->update($clientId, $domainId, $site);

        return true;
    }

    /**
     * Set the vhost's `nginx_directives` field. Idempotent — returns false
     * if the value already matches, true if updated.
     */
    public function setNginxDirectives(int $clientId, int $domainId, string $directives): bool
    {
        $site = $this->find($domainId);
        if (trim((string) ($site['nginx_directives'] ?? '')) === trim($directives)) {
            return false;
        }
        $site = $this->stripSysFields($site);
        $site['nginx_directives'] = $directives;
        $site['client_group_id'] = $this->client->clients->groupId($clientId);
        $this->update($clientId, $domainId, $site);

        return true;
    }

    /**
     * Strip ISPConfig system permission fields that must NOT be sent back
     * on an update (the panel reasserts them itself).
     *
     * @param  array<string, mixed>  $site
     * @return array<string, mixed>
     */
    private function stripSysFields(array $site): array
    {
        foreach (['sys_userid', 'sys_groupid', 'sys_perm_user', 'sys_perm_group', 'sys_perm_other'] as $f) {
            unset($site[$f]);
        }

        return $site;
    }

    // ── Alias domains (sites_web_aliasdomain_*) ───────────────────────

    /** @return array<string, mixed> */
    public function findAliasdomain(int $id): array
    {
        return $this->call('sites_web_aliasdomain_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function addAliasdomain(int $clientId, array $params): int
    {
        return (int) $this->call('sites_web_aliasdomain_add', $clientId, $params);
    }

    /** @param  array<string, mixed>  $params */
    public function updateAliasdomain(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_web_aliasdomain_update', $clientId, $id, $params);
    }

    public function deleteAliasdomain(int $id): bool
    {
        return (bool) $this->call('sites_web_aliasdomain_delete', $id);
    }

    // ── Subdomains (sites_web_subdomain_*) ────────────────────────────

    /** @return array<string, mixed> */
    public function findSubdomain(int $id): array
    {
        return $this->call('sites_web_subdomain_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function addSubdomain(int $clientId, array $params): int
    {
        return (int) $this->call('sites_web_subdomain_add', $clientId, $params);
    }

    /** @param  array<string, mixed>  $params */
    public function updateSubdomain(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_web_subdomain_update', $clientId, $id, $params);
    }

    public function deleteSubdomain(int $id): bool
    {
        return (bool) $this->call('sites_web_subdomain_delete', $id);
    }

    // ── VHost alias domains (sites_web_vhost_aliasdomain_*) ───────────

    /** @return array<string, mixed> */
    public function findVhostAliasdomain(int $id): array
    {
        return $this->call('sites_web_vhost_aliasdomain_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function addVhostAliasdomain(int $clientId, array $params): int
    {
        return (int) $this->call('sites_web_vhost_aliasdomain_add', $clientId, $params);
    }

    /** @param  array<string, mixed>  $params */
    public function updateVhostAliasdomain(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_web_vhost_aliasdomain_update', $clientId, $id, $params);
    }

    public function deleteVhostAliasdomain(int $id): bool
    {
        return (bool) $this->call('sites_web_vhost_aliasdomain_delete', $id);
    }

    // ── VHost subdomains (sites_web_vhost_subdomain_*) ────────────────

    /** @return array<string, mixed> */
    public function findVhostSubdomain(int $id): array
    {
        return $this->call('sites_web_vhost_subdomain_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function addVhostSubdomain(int $clientId, array $params): int
    {
        return (int) $this->call('sites_web_vhost_subdomain_add', $clientId, $params);
    }

    /** @param  array<string, mixed>  $params */
    public function updateVhostSubdomain(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_web_vhost_subdomain_update', $clientId, $id, $params);
    }

    public function deleteVhostSubdomain(int $id): bool
    {
        return (bool) $this->call('sites_web_vhost_subdomain_delete', $id);
    }

    // ── Web folders + folder users (sites_web_folder_* / _user_*) ─────

    /** @return array<string, mixed> */
    public function findFolder(int $id): array
    {
        return $this->call('sites_web_folder_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function addFolder(int $clientId, array $params): int
    {
        return (int) $this->call('sites_web_folder_add', $clientId, $params);
    }

    /** @param  array<string, mixed>  $params */
    public function updateFolder(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_web_folder_update', $clientId, $id, $params);
    }

    public function deleteFolder(int $id): bool
    {
        return (bool) $this->call('sites_web_folder_delete', $id);
    }

    /** @return array<string, mixed> */
    public function findFolderUser(int $id): array
    {
        return $this->call('sites_web_folder_user_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function addFolderUser(int $clientId, array $params): int
    {
        return (int) $this->call('sites_web_folder_user_add', $clientId, $params);
    }

    /** @param  array<string, mixed>  $params */
    public function updateFolderUser(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_web_folder_user_update', $clientId, $id, $params);
    }

    public function deleteFolderUser(int $id): bool
    {
        return (bool) $this->call('sites_web_folder_user_delete', $id);
    }

    // ── Redis instance per site (sites_redis_*) ───────────────────────

    /**
     * Quirk: `sites_redis_add` has the signature ($session, $params) —
     * no $client_id argument, unlike every other *_add function.
     *
     * @param  array<string, mixed>  $params
     */
    public function addRedis(array $params): int
    {
        return (int) $this->call('sites_redis_add', $params);
    }

    /** @return array<string, mixed> */
    public function findRedis(int $id): array
    {
        return $this->call('sites_redis_get', $id);
    }

    /** @param  array<string, mixed>  $params */
    public function updateRedis(int $clientId, int $id, array $params): bool
    {
        return (bool) $this->call('sites_redis_update', $clientId, $id, $params);
    }

    public function deleteRedis(int $id): bool
    {
        return (bool) $this->call('sites_redis_delete', $id);
    }

    /** @return array<int, array<string, mixed>> */
    public function allRedis(): array
    {
        $r = $this->call('sites_redis_get_all');

        return is_array($r) ? $r : [];
    }

    // ── Database version metadata ─────────────────────────────────────

    /** @return array<int, array<string, mixed>> */
    public function databaseVersions(int $serverId): array
    {
        $r = $this->call('sites_databaseversion_get', $serverId);

        return is_array($r) ? $r : [];
    }
}
